@API_URL = localhost:3000/api

@BASE_URL = https://api.stripe.com

@APP_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBhbmRleW1wMTk5NkBnbWFpbC5jb20iLCJwYXNzd29yZCI6ImFkbWluIiwiaWF0IjoxNjM5OTg4Nzc0LCJleHAiOjE2NDA1ODg3NzR9.91i36rm0qsK_6M4hRJMHewQt2zxkiTxKAvGaYq7vUyg

### REGISTER API REQUEST
POST http://{{API_URL}}/register HTTP/1.1
Content-Type: application/json

{
	"name": "Mohit",
	"email": "mohitpmp3gmail.com",
	"password": "123456",
	"city": "Haldwani",
	"state": "Uttarakhand",
	"zip": "263139",
	"country": "India",
	"mobile": "7983848236",
	"address": "xyz"	
}

### LOGIN API REQUEST

POST http://{{API_URL}}/login HTTP/1.1
Content-Type: application/json

{
	"email": "pandeymp1996@gmail.com",
	"password": "admin"
}

### GET CATEGORIES API REQUEST

GET http://{{API_URL}}/getCategories HTTP/1.1
Authorization: Bearer {{APP_TOKEN}}

### GET SUBCATEGORIES API REQUEST

GET http://{{API_URL}}/getSubCategories HTTP/1.1
Authorization: Bearer {{APP_TOKEN}}


### GET ALL PRODUCTS API REQUEST

GET http://{{API_URL}}/getProducts HTTP/1.1
Authorization: Bearer {{APP_TOKEN}}

### GET PRODUCT BY ID API REQUEST

POST http://{{API_URL}}/getProductByID HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{APP_TOKEN}}

{
	"id": "61a2891ebc9d073c1cb836e0"
}

### GET PRODUCT DETAILS API REQUEST

GET http://{{API_URL}}/getProductDetails HTTP/1.1
Authorization: Bearer {{APP_TOKEN}}

### ADD ITEM TO CART
POST http://{{API_URL}}/addItemToCart HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{APP_TOKEN}}

{
	"userID": "6187fe7cacbffaf7d01a3e23",
	"items": {
		"productID": "61a288e7bc9d073c1cb836df",
		"quantity": 1,
		"price": 20
	}
}

### GET CART ITEMS
GET http://{{API_URL}}/getCartItems HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{APP_TOKEN}}

{
	"userID": "6187fe7cacbffaf7d01a3e23"
}

### DELETE CART ITEM BY ID
DELETE http://{{API_URL}}/deleteCartItem HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{APP_TOKEN}}

{
	"userID": "6187fe7cacbffaf7d01a3e23",
	"productID": "61a288e7bc9d073c1cb836df"	
}

### EMPTY CART
DELETE http://{{API_URL}}/emptyCart HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{APP_TOKEN}}

{
	"userID": "6187fe7cacbffaf7d01a3e23"
}

### CREATE PAYMENT INTENT

POST http://{{API_URL}}/createPaymentIntent HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{APP_TOKEN}}

{
	"userID": "6187fe7cacbffaf7d01a3e23"
}


###