@API_URL = localhost:3000/api

@BASE_URL = https://api.stripe.com

@APP_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBhbmRleW1wMTk5NkBnbWFpbC5jb20iLCJwYXNzd29yZCI6ImFkbWluIiwiaWF0IjoxNjU3NjAwMjMwLCJleHAiOjE2NTgyMDAyMzB9.vdVS1nALuZDsIiiRz8oMGc8kk-P2OxXJRvSnRLpgAoM


### LOGIN API
POST http://{{API_URL}}/login HTTP/1.1
Content-Type: application/json

{
	"email": "pandeymp1996@gmail.com",
	"password": "admin"
}

### REGISTER API
POST http://{{API_URL}}/register HTTP/1.1
Content-Type: application/json

{
	"name": "Mohit",
	"email": "mohitpmp3@gmail.com",
	"password": "123456",
	"city": "Haldwani",
	"state": "Uttarakhand",
	"zip": "263139",
	"country": "India",
	"mobile": "7983848236",
	"address": "xyz"
}

### GET CATEGORIES API

GET http://{{API_URL}}/getCategories HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{APP_TOKEN}}

### GET SUBCATEGORIES API

GET http://{{API_URL}}/getSubCategoriesByID/6187fea4acbffaf7d01a3e26 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{APP_TOKEN}}

### GET PRODUCT BY ID API

GET http://{{API_URL}}/getProductsBySubcategoryID/61caf8207b480b2bfcf6d688 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{APP_TOKEN}}

### GET PRODUCT DETAILS API

GET http://{{API_URL}}/getProductDetails/6187feb6acbffaf7d01a3e2a HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{APP_TOKEN}}
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBhbmRleW1wMTk5NkBnbWFpbC5jb20iLCJwYXNzd29yZCI6ImFkbWluIiwiaWF0IjoxNjUxNzYwNTQ0LCJleHAiOjE2NTIzNjA1NDR9.yLZtycsCXOl04Rgb7dvtlrw0Ie-KCBQL1TX6Zukb6XA
### ADD ITEM TO CART API
POST http://{{API_URL}}/addItemToCart HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{APP_TOKEN}}

{
	"productID": "61d1bc25cfa792063ca5d86e"
}

### GET CART ITEMS API
GET http://{{API_URL}}/getCartItems HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{APP_TOKEN}}

### DELETE CART ITEM BY ID API
DELETE http://{{API_URL}}/deleteCartItem/61d1bb34cfa792063ca5d86d HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{APP_TOKEN}}

### CHECK COUPON API
GET http://{{API_URL}}/checkCoupon/xyz HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{APP_TOKEN}}

### FAVOURITES API
GET http://{{API_URL}}/favourite/61d1bb34cfa792063ca5d86d HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{APP_TOKEN}}

### GET FAVOURITES API
GET http://{{API_URL}}/getFavourites HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{APP_TOKEN}}

### EMPTY CART API
DELETE http://{{API_URL}}/emptyCart HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{APP_TOKEN}}

### CREATE PAYMENT INTENT API

POST http://{{API_URL}}/createPaymentIntent HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{APP_TOKEN}}

###